#include "PCH.h"

#include "Harness.h"
#include "Settings.h"

namespace
{
	void OnMessage(F4SE::MessagingInterface::Message* a_message)
	{
		switch (a_message->type) {
		case F4SE::MessagingInterface::kGameDataReady:
			// The main menu is up and form data is loaded, so the console
			// will accept `coc`.  This is where the harness takes over.
			Harness::Start();
			break;
		default:
			break;
		}
	}
}

// F4SEPlugin_Version is generated by the commonlibf4.plugin xmake rule from
// the metadata in xmake.lua -- it must NOT be declared here as well.
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_f4se)
{
	// Opens Documents/My Games/Fallout4/F4SE/fo4test.log and caches the F4SE
	// interfaces.  Add `.trampoline = true, .trampolineSize = 1u << 8` once
	// you branch-hook something; the harness only needs logging and tasks.
	F4SE::Init(a_f4se, { .log = true });

	REX::INFO("{} v{} loaded", F4SE::GetPluginName(), F4SE::GetPluginVersion());

	Settings::GetSingleton().Load();

	const auto messaging = F4SE::GetMessagingInterface();
	if (!messaging || !messaging->RegisterListener(OnMessage)) {
		REX::ERROR("failed to register the messaging listener");
		return false;
	}

	return true;
}
